server:
  port: 9000

spring:
  application:
    name: gateway
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    consul:
      host: 192.168.125.125
      port: 8500
      enabled: true
      discovery:
        enabled: true
        serviceName: gateway
        port: ${server.port}
        health-check-path: /actuator/health
        health-check-interval: 10s
        tags: gateway
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
